import { ProjectIndex } from '../../types/projectIndex';

/**
 * Build a static docs/README.md index based on what the project index contains.
 * This is generated without calling the model (deterministic).
 */
export function buildDocsIndex(index: ProjectIndex): string {
  const date = new Date().toISOString().split('T')[0];

  const lines: string[] = [
    '# Documentation Index',
    '',
    `> Auto-generated by Vue Docs Agent on ${date}`,
    '',
    '## Contents',
    '',
    '| File | Description |',
    '|------|-------------|',
    '| [navigation.md](./navigation.md) | Application routes and navigation guards |',
    '| [authentication.md](./authentication.md) | Authentication flow, guards, and token handling |',
    '| [api-endpoints.md](./api-endpoints.md) | All HTTP API endpoints grouped by resource |',
    '| [state-management.md](./state-management.md) | Vuex modules, state, getters, mutations, and actions |',
    '| [components.md](./components.md) | Reusable components — props, emits, usage |',
    '| [architecture.md](./architecture.md) | High-level system architecture overview |',
    '',
    '## Project Summary',
    '',
    `| Metric | Count |`,
    `|--------|-------|`,
    `| Routes | ${index.routes.length} |`,
    `| API Endpoints | ${index.apiEndpoints.length} |`,
    `| Vuex Modules | ${index.vuexModules.length} |`,
    `| Components | ${index.components.length} |`,
    `| Views | ${index.views.length} |`,
    `| Auth Records | ${index.auth.length} |`,
    '',
    `_Last scanned: ${index.scannedAt}_`,
  ];

  if (index.unresolved.length > 0) {
    lines.push('', '## Unresolved Files', '');
    lines.push('These files could not be fully parsed during scanning:');
    lines.push('');
    for (const f of index.unresolved) {
      lines.push(`- \`${f}\``);
    }
  }

  return lines.join('\n');
}
